# Generated by Django 3.0.3 on 2020-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200309_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', unique=True, upload_to='profile_pics'),
        ),
    ]
